version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
phases:
  install:
    runtime-versions:
        nodejs: 18
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - sed -i 's#AWS_URL#'"$AWS_URL"'#' src/environments/environment.ts
        - sed -i 's#ID_ADMIN_ROL#'"$ID_ADMIN_ROL"'#' src/environments/environment.ts
        - sed -i 's#CLIENT_ID#'"$CLIENT_ID"'#' src/environments/environment.ts
        - sed -i 's#AWS_LAMBDA_URL#'"$AWS_LAMBDA_URL"'#' src/environments/environment.ts
        - sed -i 's#USER_POOL_ID#'"$USER_POOL_ID"'#' src/environments/environment.ts
        - echo Build started
        - ng build --configuration production --aot
  post_build:
    commands:
        - aws s3 cp dist s3://${S3_BUCKET} --recursive
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
